map_type: costmap

obstacle_range: 2.0
raytrace_range: 7.0

transform_tolerance: 0.3

robot_radius: 0.5
inflation_radius: 0.5

observation_sources: laser_scan_sensor #point_cloud_sensor
# observation_sources:  point_cloud_sensor

laser_scan_sensor: {sensor_frame: /velodyne, data_type: LaserScan, topic: /velodyne/scan, marking: true, clearing: true}

# point_cloud_sensor: {sensor_frame: /velodyne, data_type: PointCloud2, topic: /velodyne_points, marking: true, clearing: true}